package io.github.lama06.lamagames.translator;

import java.util.Locale;

public enum Message {
    PREFIX_MAIN,
    PREFIX_BLOCK_PARTY,

    ERROR_PERMISSION,
    ERROR_WRONG_COMMAND_USAGE,
    ERROR_COMMAND_CONSOLE_NOT_ALLOWED,
    ERROR_GAME_NOT_FOUND,
    ERROR_MATERIAL_NOT_FOUND,
    ERROR_MATERIAL_NOT_A_BLOCK,
    ERROR_NO_TARGETED_BLOCK,
    ERROR_GAME_TYPE_NOT_FOUND,

    COMMAND_LAMAGAMES_LIST_HEADER,

    COMMAND_LAMAGAMES_START_SUCCESS,
    COMMAND_LAMAGAMES_START_FAIL,

    COMMAND_LAMAGAMES_STOP_SUCCESS,
    COMMAND_LAMAGAMES_STOP_FAIL,

    COMMAND_LAMAGAMES_ADD_GAME_SUCCESS,

    COMMAND_LAMAGAMES_DELETE_GAME_SUCCESS,

    COMMAND_LAMAGAMES_SAVE_CONFIG_SUCCESS,

    COMMAND_BLOCK_PARTY_SET_DANCE_FLOOR_SUCCESS,

    COMMAND_BLOCK_PARTY_ADD_FLOOR_SUCCESS,
    COMMAND_BLOCK_PARTY_ADD_FLOOR_NAME_TAKEN,

    COMMAND_BLOCK_PARTY_SET_DEADLY_BLOCK_SUCCESS,

    COMMAND_BLOCK_PARTY_SET_SPAWN_SUCCESS,

    COMMAND_BLOCK_PARTY_LIST_FLOORS_HEADER,

    COMMAND_BLOCK_PARTY_DELETE_FLOOR_SUCCESS,
    COMMAND_BLOCK_PARTY_DELETE_FLOOR_NOT_FOUND,

    GAME_STARTED_MSG,
    GAME_ENDED_MSG,
    GAME_STARTED_CONSOLE_MSG,
    GAME_ENDED_CONSOLE_MSG;

    public String getName() {
        return name().toLowerCase(Locale.ROOT);
    }
}
