package io.github.lama06.lamagames.translator;

import java.util.Locale;

public enum Message {
    PREFIX_MAIN,
    PREFIX_BLOCK_PARTY,

    ERROR_COMMAND_PERMISSION_REQUIRED,
    ERROR_COMMAND_WRONG_USAGE,
    ERROR_COMMAND_CONSOLE_NOT_ALLOWED,
    ERROR_COMMAND_NOT_IN_GAME_WORLD,

    COMMAND_LAMAGAMES_LIST_HEADER,
    COMMAND_LAMAGAMES_LIST_NO_GAMES,

    COMMAND_LAMAGAMES_START_SUCCESS,
    COMMAND_LAMAGAMES_START_FAIL,

    COMMAND_LAMAGAMES_STOP_SUCCESS,
    COMMAND_LAMAGAMES_STOP_FAIL,

    COMMAND_LAMAGAMES_ADD_GAME_SUCCESS,
    COMMAND_LAMAGAMES_ADD_GAME_WORLD_ALREADY_HAS_A_GAME,
    COMMAND_LAMAGAMES_ADD_GAME_GAME_TYPE_NOT_FOUND,

    COMMAND_LAMAGAMES_DELETE_GAME_SUCCESS,

    COMMAND_LAMAGAMES_SAVE_CONFIG_SUCCESS,

    COMMAND_BLOCK_PARTY_SET_DANCE_FLOOR_SUCCESS,
    COMMAND_BLOCK_PARTY_SET_DANCE_FLOOR_NO_TARGETED_BLOCK,

    COMMAND_BLOCK_PARTY_ADD_FLOOR_SUCCESS,
    COMMAND_BLOCK_PARTY_ADD_FLOOR_NAME_TAKEN,

    COMMAND_BLOCK_PARTY_SET_DEADLY_BLOCK_SUCCESS,
    COMMAND_BLOCK_PARTY_SET_DEADLY_BLOCK_MATERIAL_NOT_FOUND,

    COMMAND_BLOCK_PARTY_SET_SPAWN_SUCCESS,

    COMMAND_BLOCK_PARTY_LIST_FLOORS_HEADER,
    COMMAND_BLOCK_PARTY_LIST_FLOORS_NO_FLOORS,

    COMMAND_BLOCK_PARTY_DELETE_FLOOR_SUCCESS,
    COMMAND_BLOCK_PARTY_DELETE_FLOOR_NOT_FOUND,

    GAME_STARTED,
    GAME_ENDED,
    GAME_STARTED_CONSOLE,
    GAME_ENDED_CONSOLE;

    public String getName() {
        return name().toLowerCase(Locale.ROOT);
    }
}
